### ISSUE TITLE
install.sh npm error

### ISSUE THREAD

**Issue by Jonathan-Rosewood** [oscar-broman/ppg#2]
After [installing node.js](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions) and cloning the [repo](https://github.com/oscar-broman/ppg):

``` cpp
jonathan@server-pc:/srv/ppg$ npm update
npm ERR! Linux 3.19.0-15-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "update"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: samp-server@'>=2.0.0 <3.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5","0.1.6","0.1.7","0.1.8","0.2.0"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! Please include the following file with any support request:
npm ERR!     /srv/ppg/npm-debug.log
jonathan@server-pc:/srv/ppg$
```

**Comment by oscar-broman** [comment]
Pull from Git and try again - I messed up a version number!

Fixed in 96c456ce0efd5dfe887bf55b2be282ee48cc1a7e

**Comment by Jonathan-Rosewood** [comment]
Problem solved, but now I'm waiting for a fantastic learning log, because there are other mistakes :)

``` plain
async@1.4.2 node_modules/async
cors@2.7.1 node_modules/cors
└── vary@1.1.0
npm WARN optional dep failed, continuing fsevents@1.0.2
npm WARN unmet dependency /srv/ppg/node_modules/bower/node_modules/insight/node_modules/os-name/node_modules/win-release requires semver@'^5.0.1' but will load
npm WARN unmet dependency /srv/ppg/node_modules/bower/node_modules/semver,
npm WARN unmet dependency which is version 2.3.2
npm WARN unmet dependency /srv/ppg/node_modules/bower/node_modules/request/node_modules/form-data requires async@'~0.9.0' but will load
npm WARN unmet dependency /srv/ppg/node_modules/async,
npm WARN unmet dependency which is version 1.4.2
npm WARN unmet dependency /srv/ppg/node_modules/nodemon/node_modules/chokidar/node_modules/readdirp requires minimatch@'^2.0.10' but will load
npm WARN unmet dependency /srv/ppg/node_modules/nodemon/node_modules/minimatch,
npm WARN unmet dependency which is version 0.3.0
npm WARN unmet dependency /srv/ppg/node_modules/nodemon/node_modules/chokidar/node_modules/anymatch/node_modules/micromatch requires is-glob@'^1.1.3' but will load
npm WARN unmet dependency /srv/ppg/node_modules/nodemon/node_modules/chokidar/node_modules/is-glob,
npm WARN unmet dependency which is version 2.0.1
npm WARN unmet dependency /srv/ppg/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client requires debug@'1.0.4' but will load
npm WARN unmet dependency /srv/ppg/node_modules/socket.io/node_modules/socket.io-client/node_modules/debug,
npm WARN unmet dependency which is version 0.7.4
npm WARN unmet dependency /srv/ppg/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client requires parseuri@'0.0.4' but will load
npm WARN unmet dependency /srv/ppg/node_modules/socket.io/node_modules/socket.io-client/node_modules/parseuri,
npm WARN unmet dependency which is version 0.0.2
express@4.13.3 node_modules/express
├── escape-html@1.0.2
├── merge-descriptors@1.0.0
├── array-flatten@1.1.1
├── cookie@0.1.3
├── utils-merge@1.0.0
├── cookie-signature@1.0.6
├── vary@1.0.1
├── methods@1.1.1
├── content-type@1.0.1
├── range-parser@1.0.2
├── fresh@0.3.0
├── content-disposition@0.5.0
├── etag@1.7.0
├── serve-static@1.10.0
├── path-to-regexp@0.1.7
├── parseurl@1.3.0
├── depd@1.0.1
├── qs@4.0.0
├── on-finished@2.3.0 (ee-first@1.1.1)
├── finalhandler@0.4.0 (unpipe@1.0.0)
├── debug@2.2.0 (ms@0.7.1)
├── proxy-addr@1.0.8 (forwarded@0.1.0, ipaddr.js@1.0.1)
├── send@0.13.0 (destroy@1.0.3, statuses@1.2.1, ms@0.7.1, mime@1.3.4, http-errors@1.3.1)
├── type-is@1.6.9 (media-typer@0.3.0, mime-types@2.1.7)
└── accepts@1.2.13 (negotiator@0.5.3, mime-types@2.1.7)

> utf-8-validate@1.2.1 install /srv/ppg/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

nodemon@1.7.1 node_modules/nodemon
├── undefsafe@0.0.3
├── es6-promise@3.0.2
├── debug@2.2.0 (ms@0.7.1)
├── minimatch@0.3.0 (sigmund@1.0.1, lru-cache@2.7.0)
├── touch@1.0.0 (nopt@1.0.10)
├── lodash.defaults@3.1.2 (lodash.restparam@3.6.1, lodash.assign@3.2.0)
├── ps-tree@0.0.3 (event-stream@0.5.3)
├── update-notifier@0.5.0 (is-npm@1.0.0, semver-diff@2.0.0, chalk@1.1.1, string-length@1.0.1, repeating@1.1.3, configstore@1.2.1, latest-version@1.0.1)
└── chokidar@1.1.0 (arrify@1.0.0, path-is-absolute@1.0.0, glob-parent@2.0.0, async-each@0.1.6, is-binary-path@1.0.1, is-glob@2.0.1, readdirp@2.0.0, anymatch@1.3.0)
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:73:28)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:76:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:84:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 3.19.0-15-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /srv/ppg/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 

> bufferutil@1.2.1 install /srv/ppg/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:73:28)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:76:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:84:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 3.19.0-15-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /srv/ppg/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN optional dep failed, continuing utf-8-validate@1.2.1

> pty.js@0.3.0 install /srv/ppg/node_modules/samp-server/node_modules/pty.js
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:73:28)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:76:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:84:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 3.19.0-15-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /srv/ppg/node_modules/samp-server/node_modules/pty.js
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN optional dep failed, continuing bufferutil@1.2.1

> bufferutil@1.2.1 install /srv/ppg/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:73:28)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:76:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:84:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 3.19.0-15-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /srv/ppg/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 

> utf-8-validate@1.2.1 install /srv/ppg/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

bower@1.5.3 node_modules/bower
├── is-root@1.0.0
├── junk@1.0.2
├── stringify-object@1.0.1
├── chmodr@0.1.0
├── user-home@1.1.1
├── q@1.4.1
├── opn@1.0.2
├── abbrev@1.0.7
├── bower-endpoint-parser@0.2.2
├── bower-logger@0.2.2
├── lockfile@1.0.1
├── archy@1.0.0
├── nopt@3.0.4
├── graceful-fs@3.0.8
├── lru-cache@2.7.0
├── retry@0.6.1
├── tmp@0.0.24
├── semver@2.3.2
├── md5-hex@1.1.0 (md5-o-matic@0.1.1)
├── p-throttler@0.1.1 (q@0.9.7)
├── request-progress@0.3.1 (throttleit@0.0.2)
├── shell-quote@1.4.3 (array-reduce@0.0.0, array-map@0.0.0, array-filter@0.0.1, jsonify@0.0.0)
├── fstream@1.0.8 (inherits@2.0.1, graceful-fs@4.1.2)
├── bower-json@0.4.0 (intersect@0.0.3, deep-extend@0.2.11, graceful-fs@2.0.3)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, ansi-styles@2.1.0, supports-color@2.0.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── promptly@0.2.0 (read@1.0.7)
├── which@1.2.0 (is-absolute@0.1.7)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── fstream-ignore@1.0.2 (inherits@2.0.1, minimatch@2.0.10)
├── glob@4.5.3 (inherits@2.0.1, inflight@1.0.4, once@1.3.2, minimatch@2.0.10)
├── github@0.2.4 (mime@1.3.4)
├── rimraf@2.4.3 (glob@5.0.15)
├── tar-fs@1.8.1 (pump@1.0.0, tar-stream@1.2.1)
├── request@2.53.0 (aws-sign2@0.5.0, forever-agent@0.5.2, caseless@0.9.0, tunnel-agent@0.4.1, oauth-sign@0.6.0, stringstream@0.0.4, isstream@0.1.2, json-stringify-safe@5.0.1, tough-cookie@2.2.0, qs@2.3.3, node-uuid@1.4.3, mime-types@2.0.14, form-data@0.2.0, combined-stream@0.0.7, http-signature@0.10.1, bl@0.9.4, hawk@2.3.1)
├── cardinal@0.4.4 (ansicolors@0.2.1, redeyed@0.4.4)
├── update-notifier@0.3.2 (is-npm@1.0.0, string-length@1.0.1, semver-diff@2.0.0, latest-version@1.0.1)
├── decompress-zip@0.1.0 (mkpath@0.1.0, touch@0.0.3, readable-stream@1.1.13, binary@0.3.0)
├── bower-registry-client@0.3.0 (async@0.2.10, graceful-fs@2.0.3, request-replay@0.2.0, rimraf@2.2.8, lru-cache@2.3.1, mkdirp@0.3.5, request@2.51.0)
├── handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)
├── insight@0.7.0 (async@1.4.2, object-assign@4.0.1, tough-cookie@2.2.0, lodash.debounce@3.1.1, configstore@1.2.1, os-name@1.0.3, inquirer@0.10.1)
├── mout@0.11.0
├── bower-config@0.6.1 (osenv@0.0.3, graceful-fs@2.0.3, optimist@0.6.1, mout@0.9.1)
├── configstore@0.3.2 (object-assign@2.1.1, xdg-basedir@1.0.1, uuid@2.0.1, osenv@0.1.3, js-yaml@3.4.2)
└── inquirer@0.8.0 (ansi-regex@1.1.1, figures@1.4.0, mute-stream@0.0.4, through@2.3.8, lodash@2.4.2, readline2@0.1.1, chalk@0.5.1, rx@2.5.3, cli-color@0.3.3)
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:73:28)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:76:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:84:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 3.19.0-15-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /srv/ppg/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN optional dep failed, continuing bufferutil@1.2.1
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
socket.io@1.3.7 node_modules/socket.io
├── debug@2.1.0 (ms@0.6.2)
├── has-binary-data@0.1.3 (isarray@0.0.1)
├── socket.io-parser@2.2.4 (isarray@0.0.1, debug@0.7.4, component-emitter@1.1.2, benchmark@1.0.0, json3@3.2.6)
├── socket.io-adapter@0.3.1 (object-keys@1.0.1, debug@1.0.2, socket.io-parser@2.2.2)
├── engine.io@1.5.4 (base64id@0.1.0, debug@1.0.3, engine.io-parser@1.2.2, ws@0.8.0)
└── socket.io-client@1.3.7 (to-array@0.1.3, debug@0.7.4, indexof@0.0.1, object-component@0.0.3, component-bind@1.0.0, backo2@1.0.2, component-emitter@1.1.2, has-binary@0.1.6, parseuri@0.0.2, engine.io-client@1.5.4)
npm ERR! Linux 3.19.0-15-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "update"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /srv/ppg/npm-debug.log
bower codemirror#*          not-cached git://github.com/marijnh/CodeMirror.git#*
bower codemirror#*             resolve git://github.com/marijnh/CodeMirror.git#*
bower oauth-js#*            not-cached git://github.com/oauth-io/oauth-js.git#*
bower oauth-js#*               resolve git://github.com/oauth-io/oauth-js.git#*
bower bootstrap#*           not-cached git://github.com/twbs/bootstrap.git#*
bower bootstrap#*              resolve git://github.com/twbs/bootstrap.git#*
bower jquery#*              not-cached git://github.com/jquery/jquery.git#*
bower jquery#*                 resolve git://github.com/jquery/jquery.git#*
bower bourbon#*             not-cached git://github.com/thoughtbot/bourbon.git#*
bower bourbon#*                resolve git://github.com/thoughtbot/bourbon.git#*
bower oauth-js#*              download https://github.com/oauth-io/oauth-js/archive/0.4.3.tar.gz
bower bourbon#*               download https://github.com/thoughtbot/bourbon/archive/v4.2.5.tar.gz
bower codemirror#*            download https://github.com/marijnh/CodeMirror/archive/5.7.0.tar.gz
bower jquery#*                download https://github.com/jquery/jquery/archive/2.1.4.tar.gz
bower bootstrap#*             download https://github.com/twbs/bootstrap/archive/v3.3.5.tar.gz
bower bourbon#*                extract archive.tar.gz
bower oauth-js#*               extract archive.tar.gz
bower oauth-js#*              mismatch Version declared in the json (0.4.2) is different than the resolved one (0.4.3)
bower oauth-js#*              resolved git://github.com/oauth-io/oauth-js.git#0.4.3
bower bourbon#*               resolved git://github.com/thoughtbot/bourbon.git#4.2.5
bower jquery#*                 extract archive.tar.gz
bower font-awesome#*        not-cached git://github.com/FortAwesome/Font-Awesome.git#*
bower font-awesome#*           resolve git://github.com/FortAwesome/Font-Awesome.git#*
bower jquery#*                resolved git://github.com/jquery/jquery.git#2.1.4
bower codemirror#*             extract archive.tar.gz
bower font-awesome#*          download https://github.com/FortAwesome/Font-Awesome/archive/v4.4.0.tar.gz
bower codemirror#*            resolved git://github.com/marijnh/CodeMirror.git#5.7.0
bower bootstrap#*              extract archive.tar.gz
bower bootstrap#*             resolved git://github.com/twbs/bootstrap.git#3.3.5
bower font-awesome#*           extract archive.tar.gz
bower font-awesome#*          resolved git://github.com/FortAwesome/Font-Awesome.git#4.4.0
bower oauth-js#*               install oauth-js#0.4.3
bower bourbon#*                install bourbon#4.2.5
bower jquery#>= 1.9.1          install jquery#2.1.4
bower codemirror#*             install codemirror#5.7.0
bower bootstrap#*              install bootstrap#3.3.5
bower font-awesome#*           install font-awesome#4.4.0

oauth-js#0.4.3 public/components/oauth-js

bourbon#4.2.5 public/components/bourbon

jquery#2.1.4 public/components/jquery

codemirror#5.7.0 public/components/codemirror

bootstrap#3.3.5 public/components/bootstrap
└── jquery#2.1.4

font-awesome#4.4.0 public/components/font-awesome
```

**Comment by oscar-broman** [comment]
Which Linux OS do you have?

**Comment by Jonathan-Rosewood** [comment]
Ubuntu 15.04 arch x64

**Comment by oscar-broman** [comment]
In logs like these, look for the first `ERR` and you will usually see the initial cause.

In this case, the command `make` is missing on your system.

On Ubuntu I think you need to run this: `sudo apt-get install build-essential`

**Comment by Jonathan-Rosewood** [comment]
I completely forgot about it after the regular reinstallation. Thank you.
By the way, I wanted to offer my machine as a test platform for PPG.
The [address specified in the readme](http://www.slice-vps.nl:7070/) does not answer for me..

**Comment by oscar-broman** [comment]
Yeah, it's a very old address. If you wish to host it, I will put your address instead!

**Comment by Jonathan-Rosewood** [comment]
Of course I do not mind.
The server is running from 12 to 22 hours a day, if it meets the requirements...
Then I offer to do so - to be written off in a private chat to discuss the details :)

**Comment by oscar-broman** [comment]
Use Gitter for private chat - I'm on there

**Comment by Jonathan-Rosewood** [comment]
I posted there.
